# Generated by Django 3.1.3 on 2020-12-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
