# Generated by Django 3.1.4 on 2020-12-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20201213_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='keep_nums',
            field=models.IntegerField(default=0),
        ),
    ]
